services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD-SHELL', 'mariadb-admin ping -h 127.0.0.1 --password=$MARIADB_ROOT_PASSWORD --silent' ]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: almond
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
