CREATE TABLE IF NOT EXISTS mode (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(32) UNIQUE NOT NULL,
    guild_id BIGINT UNSIGNED NOT NULL
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS victory (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    mode_id INT NOT NULL,
    guild_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (mode_id) REFERENCES mode (id)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS updatable_message (
    id INT AUTO_INCREMENT PRIMARY KEY,
    channel_id BIGINT UNSIGNED NOT NULL,
    message_id BIGINT UNSIGNED NOT NULL,
    mode_id INT,
    guild_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (mode_id) REFERENCES mode (id)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS role (
    id INT AUTO_INCREMENT PRIMARY KEY,
    role_id BIGINT UNSIGNED NOT NULL DISTINCT,
    user_id BIGINT UNSIGNED NOT NULL DISTINCT,
    guild_id BIGINT UNSIGNED NOT NULL
);